#!/usr/bin/env bash
# Prepare a disposable SCRY_HOME + scry binary for VHS tapes.
# Seeds from examples/demo.db (scrubbed demo data — no real PII).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
TMP="$(cd "$(dirname "$0")" && pwd)/.tmp"
HOME_DIR="$TMP/home"
FAKE_HOME="$TMP/fake-home"
BIN="$TMP/scry"
DB="$HOME_DIR/scry.db"
CFG="$HOME_DIR/config.json"
ENV_SH="$TMP/env.sh"

mkdir -p "$TMP" "$HOME_DIR" "$FAKE_HOME"

echo "[tapes] building scry binary → $BIN"
CGO_ENABLED=0 go build -trimpath -o "$BIN" "$ROOT/cmd/scry"

echo "[tapes] seeding SCRY_HOME from examples/demo.db"
cp -f "$ROOT/examples/demo.db" "$DB"
rm -f "${DB}-wal" "${DB}-shm"

# Freshen the sync clock. The committed snapshot ages, and a recording that
# opens with "mirror last synced 2h ago — run `scry sync`" reads as a defect
# rather than as the freshness guard it is.
sqlite3 "$DB" "UPDATE sync_state SET watermark = strftime('%Y-%m-%dT%H:%M:%S.000Z','now'),
                                     last_full_sync_at = strftime('%Y-%m-%dT%H:%M:%S.000Z','now'),
                                     last_error = NULL;
               UPDATE items SET synced_at = strftime('%Y-%m-%dT%H:%M:%S.000Z','now');
               UPDATE sources SET synced_at = strftime('%Y-%m-%dT%H:%M:%S.000Z','now');"

# Minimal config — credential is fake; CLI reads never hit the network.
cat >"$CFG" <<'EOF'
{
  "site": "https://nimbus.example.com",
  "email": "dana@example.com",
  "token": "demo-fake-token",
  "projects": ["NMB", "NMA", "NMS"]
}
EOF

# env.sh is sourced (Hidden) by tapes so the visible prompt never shows a
# real username, hostname, or home path. PS1 is a bare dollar sign.
cat >"$ENV_SH" <<EOF
# Generated by tools/tapes/prepare.sh — do not edit.
export SCRY_HOME='$HOME_DIR'
export PATH='$TMP':"\$PATH"
export HOME='$FAKE_HOME'
export PS1='\$ '
export PROMPT_COMMAND=
unset HISTFILE
cd '$ROOT'
EOF

echo "[tapes] ready (SCRY_HOME=$HOME_DIR)"
echo "[tapes] source $ENV_SH before scry commands"
