package retro

/*
 * TestDoneWordLocaleParity — GDK-1943's recurrence layer.
 *
 * The demo fixtures are one corpus in three languages: examples/demo.db is
 * the committed English original and e2e/.tmp/demo-ko.db / demo-ja.db are
 * generated copies of it with the translation applied
 * (`GADAK_MEDIA_LOCALE=<ko|ja> make media-fixture`). Same work, three
 * vocabularies — so the mismatch heuristic counting materially differently
 * across them is a defect by construction, not a judgement call: the row is
 * measuring the language, not the work. That is how GDK-1943 opened: the
 * retro table over the release takes read 0→0 (en), 0→0 (ja) and 4→9 (ko)
 * while every other column agreed, and the direct count below measured
 * 7 / 36 / 7.
 *
 * What is counted here is the language-sensitive core of the mismatch row —
 * comments on issues not done now whose body HasDoneWord fires — rather than
 * the row itself: the row's other guards (recency against the last status
 * change, week bucketing) read the clock, and pinning a clock would make
 * this a fixture-age test instead of a language test. The core count is
 * time-independent: the fixtures are static files.
 *
 * The ko and ja fixtures are generated, not committed, so a fresh checkout
 * does not have them: the test skips cleanly, naming the make target,
 * rather than going red on files that were never built. examples/demo.db is
 * committed, so its absence is a broken checkout and fails loudly.
 */

import (
	"database/sql"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	_ "modernc.org/sqlite"
)

// localeParityTolerance is how far the three counts may drift apart before
// the gate calls it a defect.
//
// GDK-1943: after the clause rule landed the measured counts are 12 (ko) /
// 7 (en) / 7 (ja) — a gap of 5, all of it vocabulary rather than clauses:
// ko and ja write "ready" and "written" with 완료/完了 where the English
// comments say "ready"/"written" (4 hits shared with ja's own count), and 2
// ko hits are the 나머지⊃머지 substring false positive (a longer word
// containing a done word — filed as the follow-up in GDK-1943's round
// notes, a different defect genus from the clause rule this gate closed).
// Three beyond the measured gap absorbs a one-off wording choice when the
// corpus changes. The pre-fix gap was 29 (7/36/7), and any clause-shaped
// divergence — the class this gate exists to catch — clears 8 easily: one
// duplicated scheduling sentence was 24 on its own.
const localeParityTolerance = 8

// localeFixturePaths are the three translations, repo-relative to this
// package. The ko/ja pair is generated by the make target the skip names.
func localeFixturePaths() map[string]string {
	return map[string]string{
		"en": filepath.Join("..", "..", "examples", "demo.db"),
		"ko": filepath.Join("..", "..", "e2e", ".tmp", "demo-ko.db"),
		"ja": filepath.Join("..", "..", "e2e", ".tmp", "demo-ja.db"),
	}
}

// countNotDoneDoneWordComments is the gate's count over one fixture:
// comments on issues that are not done now, HasDoneWord on the body.
// The category filter mirrors Compute's comment loop exactly — status
// category by id, never by display name.
func countNotDoneDoneWordComments(t *testing.T, path string) int {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	fixtureCopy := filepath.Join(t.TempDir(), "fixture.db")
	if err := os.WriteFile(fixtureCopy, raw, 0o600); err != nil {
		t.Fatalf("copy %s: %v", path, err)
	}
	db, err := sql.Open("sqlite", "file:"+fixtureCopy)
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	rows, err := db.Query(`SELECT c.body_text FROM comments c
		JOIN issues i ON i.item_id = c.item_id
		WHERE COALESCE(i.status_category,'') != '' AND i.status_category != 'done'`)
	if err != nil {
		t.Fatalf("query %s: %v", path, err)
	}
	defer rows.Close()
	n := 0
	for rows.Next() {
		var body string
		if err := rows.Scan(&body); err != nil {
			t.Fatal(err)
		}
		if HasDoneWord(body) {
			n++
		}
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("walk %s: %v", path, err)
	}
	return n
}

// applyLocaleFixture builds the applied fixture the parity gate needs, the
// same way tools/doc-checks.sh does: a copy of the committed English mirror
// with tools/demo-i18n/apply.py run over it. Returns the path, or an error
// when the machine cannot run it at all.
func applyLocaleFixture(t *testing.T, dir, loc string) (string, error) {
	t.Helper()
	src := filepath.Join("..", "..", "examples", "demo.db")
	raw, err := os.ReadFile(src)
	if err != nil {
		return "", err
	}
	out := filepath.Join(dir, "demo-"+loc+".db")
	if err := os.WriteFile(out, raw, 0o600); err != nil {
		return "", err
	}
	cmd := exec.Command("python3", filepath.Join("..", "..", "tools", "demo-i18n", "apply.py"), out, loc)
	if msg, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("apply.py %s: %v: %s", loc, err, strings.TrimSpace(string(msg)))
	}
	return out, nil
}

func TestDoneWordLocaleParity(t *testing.T) {
	paths := localeFixturePaths()
	built := t.TempDir()
	for _, loc := range []string{"ko", "ja"} {
		if _, err := os.Stat(paths[loc]); err == nil {
			continue
		}
		// A gate that only runs where somebody happened to record a clip is
		// not a gate (GDK-1943). The translations are committed JSON and the
		// applier is a script this repo already runs from doc-checks, so the
		// fixture the parity needs can be built here in a temp directory
		// rather than waited for. Skipping is left for the one case that is
		// genuinely out of reach: a machine with no python3.
		if p, err := applyLocaleFixture(t, built, loc); err == nil {
			paths[loc] = p
		} else {
			t.Skipf("GDK-1943 locale gate: cannot build the %s fixture here (%v) — `GADAK_MEDIA_LOCALE=%s make media-fixture` builds it", loc, err, loc)
		}
	}
	counts := make(map[string]int, len(paths))
	for loc, path := range paths {
		counts[loc] = countNotDoneDoneWordComments(t, path)
	}
	lo, hi := counts["en"], counts["en"]
	for _, n := range counts {
		if n < lo {
			lo = n
		}
		if n > hi {
			hi = n
		}
	}
	if hi-lo > localeParityTolerance {
		t.Errorf("the mismatch heuristic counts materially differently across the three translations of one corpus (GDK-1943): en=%d ko=%d ja=%d, spread %d beyond tolerance %d — the row is measuring the language, not the work",
			counts["en"], counts["ko"], counts["ja"], hi-lo, localeParityTolerance)
	}
	t.Logf("GDK-1943 locale parity: en=%d ko=%d ja=%d (tolerance %d)", counts["en"], counts["ko"], counts["ja"], localeParityTolerance)
}
