/**
 * Scale flagship promo for docs/media/scale.{gif,mp4}.
 *
 * The one promise this product leads with: the tracker your company already
 * runs, read at local speed. So the clip opens on a 20,000-issue mirror —
 * the count is on screen, not claimed — and then one continuous run of the
 * daily loop: ⌘K search keeps up with fast typing (keystroke delay is
 * deliberately faster than search-demo, 70 ms vs 140 ms — the typing speed
 * is the demo), Enter lands on the hit, then the same list regroups by
 * assignee (Breakdown menu) and narrows by project (Add filter). Every
 * interaction is the product's own affordance; nothing is driven by URL.
 *
 * The mirror is examples/demo.db scaled by `gadak snapshot --scale 20000`
 * (deterministic, --seed 1) — generated by `make media-scale`, served via
 * GADAK_SEED_DB. No network, no model, no app edits, no DOM caption. The
 * boot skeleton is trimmed in export-scale.sh (-ss), not skipped here: the
 * recording must still see the list settle before the first keystroke.
 *
 * Gated by GADAK_MEDIA=1. Viewport and video size must stay 1280×800
 * (see scale.config.ts) or Playwright letterboxes the capture.
 */
import { test, expect, type Page, type TestInfo } from '@playwright/test'
import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import {
  attachConsoleErrors,
  catalogFor,
  fixtureString,
  forceLocale,
  mediaLocale,
  MEDIA_LOCALE_STAMP,
  MEDIA_SEARCH_TOKEN,
} from '../helpers'

const isMedia = !!process.env.GADAK_MEDIA

/**
 * The UI language this take records in (GADAK_MEDIA_LOCALE, default en).
 *
 * Two sources of text, and neither is restated here as a literal. Everything
 * the app renders comes out of that locale's message catalog (`t`). Everything
 * the *mirror* carries — issue titles, priority and status display names —
 * comes out of the fixture translation the Makefile applied to the copy this
 * take is recorded over (`fixtureString`, GDK-1556): the whole frame is in one
 * language, so a Korean take reads 높음 / 진행 중, not High / In Progress.
 */
const LOCALE = mediaLocale()
const t = catalogFor(LOCALE)

/** A catalog string as a literal pattern — ja and ko copy is not regex. */
const literal = (s: string): string => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

/**
 * A value row in an open filter menu, by the value it carries in the DOM.
 *
 * GDK-1557: `getByRole('button', { name: /^High\b/ })` resolved to two
 * elements under ko and ja and one under en — measured on the priority menu,
 * 2026-09-07. The second is the row's ⊘ button, whose aria-label is
 * `filter.excludeValue`: English puts the verb first ("Exclude High
 * (Alt-click)") but ko is "{value} 제외 (Alt+클릭)" and ja "{value} を除外
 * (Alt+クリック)", so in those languages the exclude button's name *starts*
 * with the value too. An accessible-name prefix is only unique in the one
 * language whose word order happens to put the label last.
 *
 * So the row is addressed by `data-filter-value` (FilterBar.svelte:290-291) —
 * the facet's own value, not a rendered label. For the status axis that is
 * the status id, which is what CLAUDE.md says to key on; for priority this
 * fixture carries no priority ids, so the value is the display name and the
 * translation supplies it.
 */
const valueRow = (menu: ReturnType<Page['locator']>, value: string) =>
  menu.locator(`[data-testid="filter-value-row"][data-filter-value=${JSON.stringify(value)}]`)

/** In Progress in this fixture. The id is the wire; the name is translated. */
const IN_PROGRESS_STATUS_ID = '3'

/** A count string from the catalog, with {n} opened up to the scaled number. */
function countText(key: 'sidebar.issueCount', n: string): RegExp {
  return new RegExp(literal(t[key]).replace('\\{n\\}', n).replace(/ /g, '\\s+'))
}

/**
 * Stamp the locale beside the take.
 *
 * Measured 2026-09-07: running `bash e2e/demo/export-scale.sh` with
 * GADAK_MEDIA_LOCALE=ja over a results directory left by an earlier English
 * take produced scale.ja.mp4 with English pixels in it, and nothing said so
 * — the export script only ever looked for a video.webm. `make media-scale`
 * happens to rm -rf the directory first, so the failure only reaches you
 * when you run the export by hand, which is exactly what MEDIA.md documents.
 * The take now says which language it is, and the export refuses a mismatch.
 */
async function stampLocale(testInfo: TestInfo): Promise<void> {
  await writeFile(join(testInfo.project.outputDir, MEDIA_LOCALE_STAMP), `${LOCALE}\n`, 'utf8')
}

/** Pause between beats so a human can read the UI. */
async function beat(page: Page, ms = 700): Promise<void> {
  await page.waitForTimeout(ms)
}


test.describe('scale demo', () => {
  test.skip(!isMedia, 'GADAK_MEDIA=1 only — media pipeline recording')

  test('20,000-issue mirror: search, open, regroup, filter', async ({ page }, testInfo) => {
    await stampLocale(testInfo)
    const errors = attachConsoleErrors(page)
    await forceLocale(page, LOCALE)
    await page.goto('/#/')
    await expect(page.getByTestId('issue-layout')).toBeVisible({ timeout: 60_000 })
    await expect(page.getByTestId('issue-list-scroller')).toBeVisible({ timeout: 60_000 })
    // The scale is the claim, so the count must be on screen before anything
    // moves. Locale-formatted ("20,000 issues"); the regex takes both separators.
    await expect(page.getByText(countText('sidebar.issueCount', '20[,.]?000')).first()).toBeVisible({
      timeout: 60_000,
    })
    await beat(page, 1400)

    // ── Beat 1: search at typing speed ──
    await page.keyboard.press('ControlOrMeta+k')
    const palette = page.getByRole('dialog', { name: t['palette.title'] })
    await expect(palette).toBeVisible()
    await beat(page, 600)

    // The token exists across titles, bodies and comments of the cloned rows
    // — English 'retry' (source: the PR row e2e/serve.sh injects on NMB-139,
    // titled "fix(NMB-139): retry budget for upload", and that thread), and
    // the word the translated mirror uses for it in ko/ja (helpers.ts
    // MEDIA_SEARCH_TOKEN). On the scaled mirror the first unified hit is
    // usually a local title match, so the snippet element is optional — the
    // hit must carry the token.
    const token = MEDIA_SEARCH_TOKEN[LOCALE]
    const tokenRE = new RegExp(literal(token), 'i')
    await page.keyboard.type(token, { delay: 70 })
    const unified = palette.getByTestId('palette-unified-issue').first()
    await expect(unified).toBeVisible({ timeout: 10_000 })
    await expect(unified).toContainText(tokenRE)
    await beat(page, 1200)

    await page.keyboard.press('Enter')
    await expect(palette).toBeHidden()
    // The top hit on the scaled mirror is the "SDK Retry" postmortem
    // document — unified search covers the wiki too. Either surface is a
    // valid landing; assert a token-titled heading is on screen.
    await expect(page.getByRole('heading', { name: tokenRE }).first()).toBeVisible()
    await beat(page, 1400)

    // Back to the list for the breakdown beat. Escape closes the detail
    // surface the way a person would.
    await page.keyboard.press('Escape')
    await expect(page.getByTestId('issue-list-scroller')).toBeVisible()
    await beat(page, 500)

    // ── Beat 2: regroup by assignee (Breakdown menu, same affordance as
    // groupby-demo.spec.ts — the menu, not a URL param) ──
    await page.getByRole('button', { name: new RegExp(literal(t['group.breakdown'])) }).click()
    const option = page.getByRole('button', { name: t['field.assignee'], exact: true })
    await expect(option).toBeVisible()
    await beat(page, 500)
    await option.click()
    await expect(page).toHaveURL(/[?&#]g=assignee(?:&|$)/)
    await expect(page.getByTestId('group-header').first()).toBeVisible()
    await beat(page, 1500)

    // ── Beat 3: three filters stack, and the facet counts react live ──
    // Same 2-step menu as triage.spec.ts (axis pick → value), but chained
    // three times with the exclude mode once (GDK-438: project NOT), so
    // the clip shows filters composing — each new menu already reflects
    // the filters before it in its facet counts.
    //
    // 1) Project ≠ NMB (per-value ⊘ — GDK-771 replaced the mode toggle)
    await page.getByTestId('filter-add').click()
    await page.getByTestId('filter-axis-jira_project').click()
    const menuP = page.locator('.anim-enter').first()
    await expect(menuP).toBeVisible()
    const nmbRow = menuP
      .locator('[data-testid="filter-value-row"][data-filter-value="NMB"]')
      .locator('..')
    await expect(nmbRow).toBeVisible()
    await nmbRow.hover()
    await beat(page, 400)
    await nmbRow.getByTestId('filter-value-exclude').click()
    await page.keyboard.press('Escape')
    // The exclusion reads as a word inside the chip ("not NMB"), and that
    // word is translated. Assert on the axis the chip carries in the DOM
    // instead — jira_project_not is the negation field's own name
    // (web/src/lib/view-config.ts NEGATION_FIELDS), so this holds in every
    // locale and says which chip it means.
    await expect(page.locator('[data-testid="filter-chip"][data-filter-field="jira_project_not"]')).toBeVisible()
    await beat(page, 900)

    // 2) Priority = High — the menu's facet counts are now computed over
    // the NMB-excluded slice, and picking High narrows again. This fixture
    // carries no priority ids (a pre-GDK-1491 scrub), so the facet value is
    // the display name and the translation is what the row is keyed by.
    const HIGH = fixtureString('catalog:priority:High')
    await page.getByTestId('filter-add').click()
    await page.getByTestId('filter-axis-priority').click()
    const menuH = page.locator('.anim-enter').first()
    await expect(menuH).toBeVisible()
    const high = valueRow(menuH, HIGH)
    await expect(high).toBeVisible()
    // What the frame shows, in this take's language.
    await expect(high).toContainText(HIGH)
    await beat(page, 600)
    await high.click()
    await page.keyboard.press('Escape')
    await expect(page.getByTestId('filter-chip').filter({ hasText: HIGH })).toBeVisible()
    await beat(page, 900)

    // 3) Status = In Progress on top of both. The axis is `status` (the
    // concrete one), not status_category: on the all-open view the category
    // picks are the view highlight, not chips (GDK-479), so a category pick
    // would not read on camera. The status facet's value is the status id
    // (measured: data-filter-value="3" for In Progress), which is the handle
    // CLAUDE.md says to key on and is the same in every language; the
    // translated display name is only asserted as what the frame shows.
    await page.getByTestId('filter-add').click()
    await page.getByTestId('filter-axis-status').click()
    const menu = page.locator('.anim-enter').first()
    await expect(menu).toBeVisible()
    const progressOption = valueRow(menu, IN_PROGRESS_STATUS_ID)
    await expect(progressOption).toBeVisible()
    await expect(progressOption).toContainText(fixtureString(`catalog:status:${IN_PROGRESS_STATUS_ID}`))
    await beat(page, 600)
    await progressOption.click()
    await page.keyboard.press('Escape')
    // Multi-picks summarize as "Status: 3" (count, not value list) under a
    // translated axis label, so the chip is identified by the axis it
    // carries in the DOM rather than by any of that text.
    await expect(page.locator('[data-testid="filter-chip"][data-filter-field="status"]')).toBeVisible()
    const listCount = page.getByTestId('list-count')
    await expect(listCount).not.toHaveText(/20[,.]?000/, { timeout: 30_000 })
    // Hold: three chips + the narrowed count together.
    await beat(page, 1800)
    await beat(page, 500)

    expect(errors, `console errors:\n${errors.join('\n')}`).toEqual([])
  })
})
