/**
 * Scale flagship promo for docs/media/scale.{gif,mp4}.
 *
 * The one promise this product leads with: the tracker your company already
 * runs, read at local speed. So the clip opens on a 20,000-issue mirror —
 * the count is on screen, not claimed — and then one continuous run of the
 * daily loop: ⌘K search keeps up with fast typing (keystroke delay is
 * deliberately faster than search-demo, 70 ms vs 140 ms — the typing speed
 * is the demo), Enter lands on the hit, then the same list regroups by
 * assignee (Breakdown menu) and narrows by project (Add filter). Every
 * interaction is the product's own affordance; nothing is driven by URL.
 *
 * The mirror is examples/demo.db scaled by `gadak snapshot --scale 20000`
 * (deterministic, --seed 1) — generated by `make media-scale`, served via
 * GADAK_SEED_DB. No network, no model, no app edits, no DOM caption. The
 * boot skeleton is trimmed in export-scale.sh (-ss), not skipped here: the
 * recording must still see the list settle before the first keystroke.
 *
 * Gated by GADAK_MEDIA=1. Viewport and video size must stay 1280×800
 * (see scale.config.ts) or Playwright letterboxes the capture.
 */
import { test, expect, type Page } from '@playwright/test'
import { attachConsoleErrors, forceLocale } from '../helpers'

const isMedia = !!process.env.GADAK_MEDIA

/** Pause between beats so a human can read the UI. */
async function beat(page: Page, ms = 700): Promise<void> {
  await page.waitForTimeout(ms)
}


test.describe('scale demo', () => {
  test.skip(!isMedia, 'GADAK_MEDIA=1 only — media pipeline recording')

  test('20,000-issue mirror: search, open, regroup, filter', async ({ page }) => {
    const errors = attachConsoleErrors(page)
    await forceLocale(page, 'en')
    await page.goto('/#/')
    await expect(page.getByTestId('issue-layout')).toBeVisible({ timeout: 60_000 })
    await expect(page.getByTestId('issue-list-scroller')).toBeVisible({ timeout: 60_000 })
    // The scale is the claim, so the count must be on screen before anything
    // moves. Locale-formatted ("20,000 issues"); the regex takes both separators.
    await expect(page.getByText(/20[,.]?000\s+issues/).first()).toBeVisible({ timeout: 60_000 })
    await beat(page, 1400)

    // ── Beat 1: search at typing speed ──
    await page.keyboard.press('ControlOrMeta+k')
    const palette = page.getByRole('dialog', { name: 'Command palette' })
    await expect(palette).toBeVisible()
    await beat(page, 600)

    // 'retry' exists across titles, bodies and comments of the cloned rows
    // (source: NMB-139 "retry budget for upload" and its thread). On the
    // scaled mirror the first unified hit is usually a local title match,
    // so the snippet element is optional — the hit must carry the token.
    await page.keyboard.type('retry', { delay: 70 })
    const unified = palette.getByTestId('palette-unified-issue').first()
    await expect(unified).toBeVisible({ timeout: 10_000 })
    await expect(unified).toContainText(/retry/i)
    await beat(page, 1200)

    await page.keyboard.press('Enter')
    await expect(palette).toBeHidden()
    // The top hit on the scaled mirror is the "SDK Retry" postmortem
    // document — unified search covers the wiki too. Either surface is a
    // valid landing; assert a retry-titled heading is on screen.
    await expect(page.getByRole('heading', { name: /retry/i }).first()).toBeVisible()
    await beat(page, 1400)

    // Back to the list for the breakdown beat. Escape closes the detail
    // surface the way a person would.
    await page.keyboard.press('Escape')
    await expect(page.getByTestId('issue-list-scroller')).toBeVisible()
    await beat(page, 500)

    // ── Beat 2: regroup by assignee (Breakdown menu, same affordance as
    // groupby-demo.spec.ts — the menu, not a URL param) ──
    await page.getByRole('button', { name: /Breakdown/ }).click()
    const option = page.getByRole('button', { name: 'Assignee', exact: true })
    await expect(option).toBeVisible()
    await beat(page, 500)
    await option.click()
    await expect(page).toHaveURL(/[?&#]g=assignee(?:&|$)/)
    await expect(page.getByTestId('group-header').first()).toBeVisible()
    await beat(page, 1500)

    // ── Beat 3: three filters stack, and the facet counts react live ──
    // Same 2-step menu as triage.spec.ts (axis pick → value), but chained
    // three times with the exclude mode once (GDK-438: project NOT), so
    // the clip shows filters composing — each new menu already reflects
    // the filters before it in its facet counts.
    //
    // 1) Project ≠ NMB (exclude mode)
    await page.getByTestId('filter-add').click()
    await page.getByTestId('filter-axis-jira_project').click()
    const excludeToggle = page.getByTestId('filter-exclude-mode')
    await expect(excludeToggle).toBeVisible()
    await excludeToggle.click()
    const menuP = page.locator('.anim-enter').first()
    await expect(menuP).toBeVisible()
    const nmb = menuP.getByRole('button', { name: /^NMB\b/ })
    await expect(nmb).toBeVisible()
    await beat(page, 400)
    await nmb.click()
    await page.keyboard.press('Escape')
    await expect(page.getByTestId('filter-chip').filter({ hasText: /not/i })).toBeVisible()
    await beat(page, 900)

    // 2) Priority = High — the menu's facet counts are now computed over
    // the NMB-excluded slice, and picking High narrows again.
    await page.getByTestId('filter-add').click()
    await page.getByTestId('filter-axis-priority').click()
    const menuH = page.locator('.anim-enter').first()
    await expect(menuH).toBeVisible()
    const high = menuH.getByRole('button', { name: /^High\b/ })
    await expect(high).toBeVisible()
    await beat(page, 600)
    await high.click()
    await page.keyboard.press('Escape')
    await expect(page.getByTestId('filter-chip').filter({ hasText: 'High' })).toBeVisible()
    await beat(page, 900)

    // 3) Status = In Progress on top of both. The axis is `status` (the
    // concrete one), not status_category: on the all-open view the category
    // picks are the view highlight, not chips (GDK-479), so a category pick
    // would not read on camera. The value buttons carry no
    // testid, so scope to the open menu (the anim-enter popover) before
    // the role lookup — otherwise a list row with matching aria wins.
    await page.getByTestId('filter-add').click()
    await page.getByTestId('filter-axis-status').click()
    const menu = page.locator('.anim-enter').first()
    await expect(menu).toBeVisible()
    const progressOption = menu.getByRole('button', { name: /^In Progress/ }).first()
    await expect(progressOption).toBeVisible()
    await beat(page, 600)
    await progressOption.click()
    await page.keyboard.press('Escape')
    // Multi-picks summarize as "Status: 3" (count, not value list), so match
    // the axis label, not the value.
    await expect(page.getByTestId('filter-chip').filter({ hasText: /^Status:/ })).toBeVisible()
    const listCount = page.getByTestId('list-count')
    await expect(listCount).not.toHaveText(/20[,.]?000/, { timeout: 30_000 })
    // Hold: three chips + the narrowed count together.
    await beat(page, 1800)
    await beat(page, 500)

    expect(errors, `console errors:\n${errors.join('\n')}`).toEqual([])
  })
})
