// Package snapshot builds shareable mirror copies for demos and benchmarks.
// See specs/000-product/contracts/sync.md "Snapshot generation".
package snapshot

import (
	"context"
	"database/sql"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"time"

	"github.com/midagedev/gadak/internal/store"

	_ "modernc.org/sqlite"
)

// Options controls snapshot generation. Now is injectable for deterministic tests.
type Options struct {
	From   string
	Out    string
	Spread time.Duration // 0 = keep source timestamps
	Scale  int           // target issue count; ≤ source count means no cloning
	Seed   int64         // reserved for determinism; algorithm itself is seed-stable
	Force  bool
	Now    time.Time
	// DeriveSprints invents a sprint history from fix versions named
	// "Sprint N" (the demo fixture's convention) when the source has no
	// sprints of its own — see deriveSprints (GDK-1656).
	DeriveSprints bool
}

// Result is the human-readable summary of a successful Build.
type Result struct {
	Path      string
	Issues    int
	Comments  int
	Changelog int
	Spread    time.Duration
	Scale     int
	Bytes     int64
	// Facet rotation (GDK-1558), zero when nothing was cloned: the size of the
	// two value pools the clones rotate through and the length of the weighted
	// sequence (one entry per source issue). Reported so "did the rotation
	// happen, and over what" is answered by the command that did it.
	Assignees   int
	Priorities  int
	SequenceLen int
	// Flow is what the snapshot's own timestamps say about how work moves
	// through it (GDK-1739). Always measured, always printed: the defect this
	// answers — a fixture whose WIP was two months old and whose cycle time
	// was an afternoon — took a hand-written SQL probe to see, on a file that
	// is regenerated by a Makefile target nobody watches.
	Flow FlowStats
}

// FlowStats is the distribution `gadak snapshot` reports about the file it
// just wrote. Ages and cycles are days.
type FlowStats struct {
	WIPCount                        int
	WIPAgeP50, WIPAgeP85, WIPAgeMax float64
	CycleCount                      int
	CycleP50, CycleP85, CycleMax    float64
	Closed, ClosedThroughProgress   int
}

// String is the one line the command prints.
func (f FlowStats) String() string {
	pct := 0.0
	if f.Closed > 0 {
		pct = 100 * float64(f.ClosedThroughProgress) / float64(f.Closed)
	}
	return fmt.Sprintf(
		"flow: wip n=%d age p50 %.1fd p85 %.1fd max %.1fd | cycle n=%d p50 %.1fd p85 %.1fd max %.1fd | closed via In Progress %d/%d (%.0f%%)",
		f.WIPCount, f.WIPAgeP50, f.WIPAgeP85, f.WIPAgeMax,
		f.CycleCount, f.CycleP50, f.CycleP85, f.CycleMax,
		f.ClosedThroughProgress, f.Closed, pct)
}

// flowStats reads the four numbers back off the written file rather than
// reporting what the placement intended: the columns are re-derived by
// store.BackfillFlow from the changelog, so anything measured earlier would be
// a claim about the plan and not about the artefact.
//
// Categories come from issues_raw.status_category, which is what
// deriveStatusCatalog keys the snapshot's own catalog from — never a display
// name (project CLAUDE.md).
func flowStats(db *sql.DB, now time.Time) (FlowStats, error) {
	var f FlowStats
	nowStr := formatTime(now)
	ages, err := queryFloats(db, `
		SELECT (julianday(?) - julianday(started_at)) FROM issues_raw
		WHERE status_category = 'inprogress' AND started_at IS NOT NULL AND started_at != ''
		ORDER BY 1`, nowStr)
	if err != nil {
		return f, err
	}
	f.WIPCount = len(ages)
	f.WIPAgeP50, f.WIPAgeP85, f.WIPAgeMax = quantile(ages, 0.50), quantile(ages, 0.85), quantile(ages, 1)

	cycles, err := queryFloats(db, `
		SELECT cycle_hours / 24.0 FROM issues_raw
		WHERE status_category = 'done' AND cycle_hours IS NOT NULL
		ORDER BY 1`)
	if err != nil {
		return f, err
	}
	f.CycleCount = len(cycles)
	f.CycleP50, f.CycleP85, f.CycleMax = quantile(cycles, 0.50), quantile(cycles, 0.85), quantile(cycles, 1)

	if err := db.QueryRow(`
		SELECT COUNT(*),
		       COALESCE(SUM(CASE WHEN started_at IS NOT NULL AND started_at != ''
		                          AND resolved_at IS NOT NULL AND started_at < resolved_at
		                         THEN 1 ELSE 0 END), 0)
		FROM issues_raw WHERE status_category = 'done'`).
		Scan(&f.Closed, &f.ClosedThroughProgress); err != nil {
		return f, err
	}
	return f, nil
}

func queryFloats(db *sql.DB, query string, args ...any) ([]float64, error) {
	rows, err := db.Query(query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []float64
	for rows.Next() {
		var v sql.NullFloat64
		if err := rows.Scan(&v); err != nil {
			return nil, err
		}
		if v.Valid {
			out = append(out, v.Float64)
		}
	}
	return out, rows.Err()
}

// quantile reads p off an already-sorted slice, nearest rank.
func quantile(sorted []float64, p float64) float64 {
	if len(sorted) == 0 {
		return 0
	}
	i := int(math.Round(p * float64(len(sorted)-1)))
	return sorted[i]
}

// Build creates a new shareable database at opts.Out from opts.From.
// Output is written via a temp file and renamed only after a credential scan.
func Build(opts Options) (Result, error) {
	var zero Result
	if opts.Out == "" {
		return zero, fmt.Errorf("output path is required")
	}
	if opts.From == "" {
		return zero, fmt.Errorf("source path is required")
	}
	if !opts.Now.IsZero() {
		opts.Now = opts.Now.UTC()
	}
	if opts.Seed == 0 {
		opts.Seed = 1
	}
	// Seed keys the per-issue synthetic lifetimes (internal/snapshot/lifetime.go).
	// Everything else in the pipeline is deterministic without an RNG.

	if _, err := os.Stat(opts.From); err != nil {
		return zero, fmt.Errorf("source %q: %w", opts.From, err)
	}
	if _, err := os.Stat(opts.Out); err == nil && !opts.Force {
		return zero, fmt.Errorf("output %q already exists (pass --force to overwrite)", opts.Out)
	}

	// "now" is the wall clock unless the caller pins it. Anchoring to the
	// source's own latest timestamp would make every build reproducible for
	// free, but it also freezes the snapshot in the past: sources.synced_at
	// would land back when the mirror was last synced, and the sync-health
	// badge reads that field, so a fresh snapshot would show as permanently
	// delayed (docs/project/STATE_OF_PLAY.md, hard-won knowledge #13). Reproducible
	// builds pass --now instead.
	if opts.Now.IsZero() {
		opts.Now = time.Now().UTC()
	}

	tmp := fmt.Sprintf("%s.tmp-%d", opts.Out, os.Getpid())
	_ = os.Remove(tmp)
	_ = os.Remove(tmp + "-wal")
	_ = os.Remove(tmp + "-shm")
	cleanupTmp := true
	defer func() {
		if !cleanupTmp {
			return
		}
		_ = os.Remove(tmp)
		_ = os.Remove(tmp + "-wal")
		_ = os.Remove(tmp + "-shm")
	}()

	rot, err := buildInto(tmp, opts)
	if err != nil {
		return zero, err
	}

	// The column-bag copier drops the flow columns by design: issueColumns is
	// the destination's static list, and spread moves the very stamps a
	// copied started_at / cycle_hours / last_activity_at would disagree with.
	// They land at their DEFAULT and are re-derived from the destination's
	// own spread rows here (store.BackfillFlow, the v43 migration hook), so
	// the shipped flow columns always agree with the timestamps the snapshot
	// actually carries. open_blockers rides the same call's full sweep.
	sdb, err := store.Open(tmp)
	if err != nil {
		return zero, err
	}
	if err := sdb.BackfillFlow(context.Background()); err != nil {
		_ = sdb.Close()
		return zero, fmt.Errorf("backfill flow columns: %w", err)
	}
	if err := sdb.Close(); err != nil {
		return zero, err
	}

	// Credential scan before publish. The same handle reads back the flow
	// distribution the spread just produced (GDK-1739) — see flowStats.
	scanDB, err := openSQLite(tmp, false)
	if err != nil {
		return zero, err
	}
	scanErr := scanCredentials(scanDB)
	flow, flowErr := flowStats(scanDB, opts.Now)
	_ = scanDB.Close()
	if scanErr != nil {
		return zero, scanErr
	}
	if flowErr != nil {
		return zero, fmt.Errorf("flow stats: %w", flowErr)
	}

	// Publish: remove destination if force, then rename.
	if opts.Force {
		_ = os.Remove(opts.Out)
		_ = os.Remove(opts.Out + "-wal")
		_ = os.Remove(opts.Out + "-shm")
	}
	if err := os.Rename(tmp, opts.Out); err != nil {
		// Cross-device rename can fail; fall back to copy+remove.
		if err := copyFile(tmp, opts.Out); err != nil {
			return zero, fmt.Errorf("publish snapshot: %w", err)
		}
		_ = os.Remove(tmp)
	}
	cleanupTmp = false

	info, err := os.Stat(opts.Out)
	if err != nil {
		return zero, err
	}
	counts, err := countMain(opts.Out)
	if err != nil {
		return zero, err
	}
	return Result{
		Path:      opts.Out,
		Issues:    counts.issues,
		Comments:  counts.comments,
		Changelog: counts.changelog,
		Spread:    opts.Spread,
		Scale:     opts.Scale,
		Bytes:     info.Size(),

		Assignees:   rot.assignees,
		Priorities:  rot.priorities,
		SequenceLen: rot.sequenceLen,
		Flow:        flow,
	}, nil
}

type counts struct {
	issues, comments, changelog int
}

func countMain(path string) (counts, error) {
	var c counts
	db, err := openSQLite(path, true)
	if err != nil {
		return c, err
	}
	defer db.Close()
	if err := db.QueryRow(`SELECT COUNT(*) FROM issues`).Scan(&c.issues); err != nil {
		return c, err
	}
	if err := db.QueryRow(`SELECT COUNT(*) FROM comments`).Scan(&c.comments); err != nil {
		return c, err
	}
	if err := db.QueryRow(`SELECT COUNT(*) FROM changelog`).Scan(&c.changelog); err != nil {
		return c, err
	}
	return c, nil
}

// plannedIssue is one output issue (original or clone) with optional remapped times.
type plannedIssue struct {
	src      issueRow
	cloneSeq int // 0 = original
	// remapped timestamps (empty strings mean keep source)
	createdAt, updatedAt          string
	statusChangedAt, resolvedAt   string
	reopenedAt, assigneeChangedAt string
	itemCreatedAt, itemUpdatedAt  string
	itemSyncedAt                  string
	// for linear mapping of children
	srcLo, srcHi, dstLo, dstHi time.Time
	useMap                     bool
	zeroSpan                   bool
	// events holds the re-spaced destination stamp for every dated child row
	// (internal/snapshot/lifetime.go, placeEvents), indexed the same way
	// children holds them. Empty when the issue has no dated history.
	events eventPlacement
	// Facet rotation (GDK-1558): non-nil on clones only. A clone keeps its
	// source's title, body, comments, status and changelog, so without this a
	// filtered slice — "my Highest issues in progress" — is one issue repeated
	// as many times as the source was cloned. Both bags are values the source
	// itself carries; nothing is invented.
	rotAssignee *assigneeTriple
	rotPriority *priorityTriple
}

// assigneeTriple is the (assignee, assignee_id, assignee_email) bag rotated
// onto clones. The unassigned bag is a pool member like any other when the
// source has unassigned issues.
type assigneeTriple struct {
	name, id, email nullText
}

// priorityTriple is the (priority, priority_id, priority_rank) bag rotated
// onto clones. priority_id is empty in sources whose origin never sent ids
// (examples/demo.db is one) — the pool carries whatever the source has and
// fabricates nothing.
type priorityTriple struct {
	name, id nullText
	rank     int
}

// nullText keeps a nullable TEXT column's NULL apart from its empty string.
// issues_raw.assignee is nullable and "unassigned" is NULL there, never the
// empty string — a rotation that wrote the empty string instead would quietly
// stop matching every `assignee IS NULL` filter in the product while every
// count stayed right. Comparable, so it can be a pool map key.
type nullText struct {
	s     string
	valid bool
}

func textOf(v any) nullText {
	if v == nil {
		return nullText{}
	}
	return nullText{s: asString(v), valid: true}
}

// value is what goes back into the column bag: nil for NULL, so insertRow
// falls through to notNullDefaults exactly as a missing source value would.
func (n nullText) value() any {
	if !n.valid {
		return nil
	}
	return n.s
}

func (n nullText) less(o nullText) bool {
	if n.s != o.s {
		return n.s < o.s
	}
	return !n.valid && o.valid
}

type issueRow struct {
	itemID, key, projectKey string
	createdAt, updatedAt    string
	// full column bags for insert
	itemCols  map[string]any
	issueCols map[string]any
}

type children struct {
	comments    []map[string]any
	attachments []map[string]any
	changelog   []map[string]any
	// by item_id
	commentsBy    map[string][]map[string]any
	attachmentsBy map[string][]map[string]any
	changelogBy   map[string][]map[string]any
}

// pageRow is one document (items row + pages projection) for snapshot copy.
type pageRow struct {
	itemID, key        string
	createdAt          string
	itemCols, pageCols map[string]any

	// Spread output, mirroring plannedIssue: useMap set means
	// insertPageBundle writes the stamps below and rewrites the page's dated
	// children from events. A page that rode no spread keeps source stamps.
	useMap                       bool
	itemCreatedAt, itemUpdatedAt string
	itemSyncedAt                 string
	events                       eventPlacement
}

func openSQLite(path string, readOnly bool) (*sql.DB, error) {
	mode := "rwc"
	if readOnly {
		mode = "ro"
	}
	// Single-writer one-shot. busy_timeout is already set. Do not add WAL:
	// the snapshot is a shareable artifact and build.go forces journal_mode
	// DELETE on the dest so the output is a single file. synchronous is left
	// at SQLite's default for the same reason — it is part of what ships.
	dsn := "file:" + path + "?mode=" + mode +
		"&_pragma=busy_timeout(5000)&_pragma=foreign_keys(1)"
	db, err := sql.Open("sqlite", dsn)
	if err != nil {
		return nil, err
	}
	if err := db.Ping(); err != nil {
		db.Close()
		return nil, err
	}
	return db, nil
}

func copyFile(src, dst string) error {
	in, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(dst), 0o700); err != nil {
		return err
	}
	return os.WriteFile(dst, in, 0o600)
}
