// Dimension-token validation (dim-token chunk 1) — the sibling of the color
// side of this package. The embedded dim-catalog.json is generated by
// tools/dim-catalog.mjs (spacing/type defaults from web/src/app.css @theme,
// layout defaults from the JS-owned constants the generator tables), and the
// shapes are pinned together by TestDimCatalogShape the way
// TestCatalogShape pins catalog.json.
//
// No color math runs here by design: a length has no hex form, no ΔEok and
// no contrast. The write-time rules are instead:
//
//	length   px lengths are non-negative integers or one-decimal values with
//	         a lowercase px suffix ("44px", "42.5px"); line-heights (unit
//	         none) are unitless with one or two decimals ("1.4", "1.35").
//	         Stricter-than-CSS on purpose (the parseHex precedent: stricter
//	         can only refuse, never misread).
//	range    every validated-range token carries min/max in the catalog;
//	         bounds are inclusive. Where the lower bound is a cross-token
//	         relation instead of a constant (row-excerpt, detail-max) the
//	         catalog omits min and the relation below owns it.
//	relation five cross-token rules from the chunk-1 spec (control-sm ≤
//	         control, row-excerpt ≥ row+8, detail-max ≥ detail-min,
//	         overlay-max ≤ shell-max, sidebar-narrow ≤ sidebar) plus the
//	         census type-step gap (neighbors ≥ 2px apart). Relations judge
//	         the EFFECTIVE set — defaults fill whatever the user did not
//	         override — and run only when a participant was overridden, like
//	         the color group rules.
//	locked   layout.docked-min is the derived dock floor
//	         (sidebar+list-min+detail-min). Writes are refused; the runtime
//	         recomputes it from the three track tokens.
//
// Input defense mirrors the color contract (GDK-769 axis 3): unknown axis
// ids and unknown token names produce warn-severity violations and are
// carried, never a panic and never a refused save — a config written by a
// newer gadak must keep loading.
package tokencheck

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"
)

//go:embed dim-catalog.json
var dimCatalogJSON []byte

// DimToken is one entry of the generated dimension catalog. Min/Max are
// pointers so an omitted bound (relation-owned lower bounds, the locked
// token) stays absent rather than reading as zero.
type DimToken struct {
	CSSVar  string   `json:"cssVar"`
	Default string   `json:"default"`
	Tier    string   `json:"tier"`
	Unit    string   `json:"unit"`
	Min     *float64 `json:"min"`
	Max     *float64 `json:"max"`
}

type dimAxis struct {
	ID        string              `json:"id"`
	CSSPrefix string              `json:"cssPrefix"`
	Tokens    map[string]DimToken `json:"tokens"`
}

type dimCatalogFile struct {
	Axes []dimAxis `json:"axes"`
}

var (
	dimOnce sync.Once
	dimVal  dimCatalogFile
	dimIdx  map[string]dimAxis
)

func dimCatalog() (dimCatalogFile, map[string]dimAxis) {
	dimOnce.Do(func() {
		dimIdx = map[string]dimAxis{}
		if err := json.Unmarshal(dimCatalogJSON, &dimVal); err != nil {
			// Generated and committed; a parse failure is a build defect.
			// The zero catalog reports unknown for every lookup, which
			// refuses writes loudly instead of panicking.
			return
		}
		for _, ax := range dimVal.Axes {
			dimIdx[ax.ID] = ax
		}
	})
	return dimVal, dimIdx
}

// DimAxes returns the dimension axis ids in catalog order.
func DimAxes() []string {
	cat, _ := dimCatalog()
	out := make([]string, 0, len(cat.Axes))
	for _, ax := range cat.Axes {
		out = append(out, ax.ID)
	}
	return out
}

// DimTokenOf looks up one dimension token by bare name ("row") or its CSS
// variable form ("--spacing-row"). ok is false for names the catalog does
// not carry.
func DimTokenOf(axis, name string) (DimToken, bool) {
	_, idx := dimCatalog()
	ax, ok := idx[axis]
	if !ok {
		return DimToken{}, false
	}
	t, ok := ax.Tokens[normalizeDimName(ax, name)]
	return t, ok
}

func normalizeDimName(ax dimAxis, k string) string {
	return strings.TrimPrefix(strings.TrimSpace(k), ax.CSSPrefix)
}

var (
	dimPxRe       = regexp.MustCompile(`^[0-9]+(\.[0-9])?px$`)
	dimUnitlessRe = regexp.MustCompile(`^[0-9]+\.[0-9]{1,2}$`)
)

// ParseValue parses v according to the token unit and reports the numeric
// value. px requires a positive number; unitless accepts the line-height
// shape. Use ok, not the value, as the verdict.
func (t DimToken) ParseValue(v string) (float64, bool) {
	s := strings.TrimSpace(v)
	switch t.Unit {
	case "px":
		if !dimPxRe.MatchString(s) {
			return 0, false
		}
		n, err := strconv.ParseFloat(strings.TrimSuffix(s, "px"), 64)
		if err != nil || n <= 0 {
			return 0, false
		}
		return n, true
	case "none":
		if !dimUnitlessRe.MatchString(s) {
			return 0, false
		}
		n, err := strconv.ParseFloat(s, 64)
		if err != nil || n <= 0 {
			return 0, false
		}
		return n, true
	}
	return 0, false
}

// dimFormat renders a numeric dimension value with its unit for messages.
func (t DimToken) dimFormat(v float64) string {
	if t.Unit == "none" {
		return strconv.FormatFloat(v, 'f', -1, 64)
	}
	return strconv.FormatFloat(v, 'f', -1, 64) + "px"
}

// dimBounds renders the catalog range of the token for messages.
func (t DimToken) dimBounds() string {
	suffix := ""
	if t.Unit != "none" {
		suffix = "px"
	}
	fmtNum := func(v float64) string {
		return strconv.FormatFloat(v, 'f', -1, 64) + suffix
	}
	switch {
	case t.Min != nil && t.Max != nil:
		return fmtNum(*t.Min) + "–" + fmtNum(*t.Max)
	case t.Max != nil:
		return "≤ " + fmtNum(*t.Max)
	case t.Min != nil:
		return "≥ " + fmtNum(*t.Min)
	}
	return ""
}

// dimRelation is one cross-token rule. kind:
//
//	le      a ≤ b
//	ge      a ≥ b
//	ge_add  a ≥ b + add
type dimRelation struct {
	axis string
	a, b string
	kind string
	add  float64
	why  string
}

// The five relations of the chunk-1 spec plus the census type-step gap.
// row-excerpt uses +8 (the spec figure; the census draft said +12 — the
// tighter of the two is trivially addable if the lead confirms a typo).
var dimRelations = []dimRelation{
	{"spacing", "control-sm", "control", "le", 0, "the small control rides inside the regular one"},
	{"spacing", "row-excerpt", "row", "ge_add", 8, "a row carrying a preview line needs headroom"},
	{"layout", "detail-max", "detail-min", "ge", 0, "the docked panel cannot be narrower than its floor"},
	{"layout", "overlay-max", "shell-max", "le", 0, "the overlay panel cannot outgrow the shell"},
	{"layout", "sidebar-narrow", "sidebar", "le", 0, "the narrow sidebar step must not exceed the default"},
	{"type", "body", "micro", "ge_add", 2, "type steps closer than 2px read as noise, not hierarchy"},
	{"type", "title", "body", "ge_add", 2, "type steps closer than 2px read as noise, not hierarchy"},
	{"type", "heading", "title", "ge_add", 2, "type steps closer than 2px read as noise, not hierarchy"},
}

// ValidateDimensions is the write gate for the dimension axes: tier, length
// format, range and cross-token relations. Input is axis id → token name →
// value; names may be bare ("row") or CSS variables ("--spacing-row").
// Unknown axis ids and unknown names warn and are carried (GDK-769 axis 3);
// everything else that fails refuses.
func ValidateDimensions(axes map[string]map[string]string) []Violation {
	cat, idx := dimCatalog()
	var vs []Violation

	eff := map[string]map[string]float64{}
	overridden := map[string]map[string]bool{}
	for _, ax := range cat.Axes {
		eff[ax.ID] = map[string]float64{}
		overridden[ax.ID] = map[string]bool{}
		for name, tok := range ax.Tokens {
			if v, ok := tok.ParseValue(tok.Default); ok {
				eff[ax.ID][name] = v
			}
		}
		in := axes[ax.ID]
		if len(in) == 0 {
			continue
		}
		keys := make([]string, 0, len(in))
		for k := range in {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			name := normalizeDimName(ax, k)
			value := strings.TrimSpace(in[k])
			tok, known := ax.Tokens[name]
			if !known {
				vs = append(vs, Violation{
					Token:    name,
					Rule:     "unknown-token",
					Severity: SeverityWarn,
					Measured: quote(value),
					Message:  fmt.Sprintf("%s is not in the dimension catalog; ignored (a newer catalog may have renamed it)", echoDimKey(ax, k)),
				})
				continue
			}
			if tok.Tier == "locked" {
				vs = append(vs, Violation{
					Token:    name,
					Rule:     "locked",
					Severity: SeverityReject,
					Measured: quote(value),
					Floor:    "no override",
					Message: fmt.Sprintf("%s is locked (derived: sidebar + list-min + detail-min): a derived sum, not a runtime override — set those three and it is recomputed",
						tok.CSSVar),
				})
				continue
			}
			v, ok := tok.ParseValue(value)
			if !ok {
				vs = append(vs, Violation{
					Token:    name,
					Rule:     "length",
					Severity: SeverityReject,
					Measured: quote(value),
					Floor:    tok.dimExample(),
					Message:  fmt.Sprintf("%s: %s is %s", tok.CSSVar, quote(value), tok.dimExampleLong()),
				})
				continue
			}
			if (tok.Min != nil && v < *tok.Min) || (tok.Max != nil && v > *tok.Max) {
				vs = append(vs, Violation{
					Token:    name,
					Rule:     "range",
					Severity: SeverityReject,
					Measured: tok.dimFormat(v),
					Floor:    tok.dimBounds(),
					Message:  fmt.Sprintf("%s: %s is outside its range %s", tok.CSSVar, value, tok.dimBounds()),
				})
				continue
			}
			eff[ax.ID][name] = v
			overridden[ax.ID][name] = true
		}
	}

	// Defensive: the settings layer refuses unknown axes at parse time, but
	// a direct caller (or a hand-edited payload) can still land one here.
	axisIDs := make([]string, 0, len(axes))
	for id := range axes {
		axisIDs = append(axisIDs, id)
	}
	sort.Strings(axisIDs)
	for _, id := range axisIDs {
		if len(axes[id]) == 0 {
			continue
		}
		if _, ok := idx[id]; !ok {
			vs = append(vs, Violation{
				Token:    id,
				Rule:     "unknown-axis",
				Severity: SeverityWarn,
				Message: fmt.Sprintf("axis %q is not a dimension axis this build ships (%s); carried but not validated",
					id, strings.Join(DimAxes(), ", ")),
			})
		}
	}

	vs = append(vs, checkDimRelations(eff, overridden)...)
	return vs
}

// echoDimKey reproduces the CSS-variable spelling of a user key for
// messages when the name is unknown (the color side does the same by
// printing --color-<name>).
func echoDimKey(ax dimAxis, k string) string {
	k = strings.TrimSpace(k)
	if strings.HasPrefix(k, ax.CSSPrefix) {
		return k
	}
	return ax.CSSPrefix + k
}

// dimExample is the one-line accepted shape of the value.
func (t DimToken) dimExample() string {
	if t.Unit == "none" {
		return "1.4"
	}
	return "44px"
}

func (t DimToken) dimExampleLong() string {
	if t.Unit == "none" {
		return "not a unitless line height (one or two decimals, e.g. \"1.4\")"
	}
	return "not a px length (integer or one decimal, e.g. \"44px\")"
}

// checkDimRelations judges the effective dimension set. Each rule runs only
// when one of its participants was overridden — untouched defaults satisfy
// them by construction and would only add noise.
func checkDimRelations(eff map[string]map[string]float64, overridden map[string]map[string]bool) []Violation {
	_, idx := dimCatalog()
	var vs []Violation
	for _, rel := range dimRelations {
		ax, ok := idx[rel.axis]
		if !ok {
			continue
		}
		tokA, okA := ax.Tokens[rel.a]
		tokB, okB := ax.Tokens[rel.b]
		if !okA || !okB {
			continue
		}
		if !overridden[rel.axis][rel.a] && !overridden[rel.axis][rel.b] {
			continue
		}
		va, oka := eff[rel.axis][rel.a]
		vb, okb := eff[rel.axis][rel.b]
		if !oka || !okb {
			continue
		}
		bad := false
		switch rel.kind {
		case "le":
			bad = va > vb
		case "ge":
			bad = va < vb
		case "ge_add":
			bad = va < vb+rel.add
		}
		if !bad {
			continue
		}
		vs = append(vs, Violation{
			Token:    dimBlame(overridden[rel.axis], rel.a, rel.b),
			Rule:     "relation",
			Severity: SeverityReject,
			Measured: tokA.dimFormat(va),
			Floor:    dimFloor(tokB, vb, rel),
			Message:  fmt.Sprintf("%s %s must be %s %s (%s)", tokA.CSSVar, tokA.dimFormat(va), rel.opWord(), dimFloor(tokB, vb, rel), rel.why),
		})
	}
	return vs
}

// dimFloor renders the right-hand bound of a relation for Floor/Message.
func dimFloor(tokB DimToken, vb float64, rel dimRelation) string {
	switch rel.kind {
	case "ge_add":
		return tokB.dimFormat(vb) + " + " + tokB.dimFormat(rel.add)
	default:
		return tokB.dimFormat(vb)
	}
}

func (r dimRelation) opWord() string {
	switch r.kind {
	case "le":
		return "≤"
	case "ge", "ge_add":
		return "≥"
	}
	return "?"
}

// dimBlame names the token a relation violation belongs to: the overridden
// half when exactly one was overridden, both names otherwise (blame rules).
func dimBlame(overridden map[string]bool, a, b string) string {
	oa, ob := overridden[a], overridden[b]
	switch {
	case oa && !ob:
		return a
	case ob && !oa:
		return b
	default:
		return a + "/" + b
	}
}
