package tokencheck

/*
 * Dimension-catalog contract ↔ assertion map (dim-token chunk 1).
 *
 * The catalog (dim-catalog.json, generated by tools/dim-catalog.mjs) is the
 * single source of the v1 dimension surface: 19 writable tokens (spacing 4,
 * layout 7, type 8 = 4 sizes + 4 line-heights) plus docked-min locked as the
 * derived sum. Every range below comes from the census Q6 table
 * (scratch/dimwave/census.md); the relation list comes from the chunk-1 spec
 * with the type-step ≥2px gap carried from the census.
 *
 *	contract                              assertion
 *	────────────────────────────────────  ─────────────────────────────────────
 *	catalog axes and tiers are as shipped TestDimCatalogShape
 *	docked-min default is the derived sum TestDimCatalogShape
 *	defaults sit inside their own ranges  TestDimCatalogShape
 *	px lengths: int/1-decimal, positive  TestDimParseLength
 *	line-heights: unitless 1–2 decimals   TestDimParseUnitless
 *	valid partial overrides pass          TestValidateDimensionsAccepts
 *	unknown axis/token carried + warned   TestValidateDimensionsUnknownCarried
 *	locked docked-min refuses writes      TestValidateDimensionsLocked
 *	bad length / out of range refused     TestValidateDimensionsValues
 *	relations judged against defaults     TestValidateDimensionsRelations
 *	boundary values accept                TestValidateDimensionsBoundaries
 *	deterministic output                  TestDimDeterminism
 */

import (
	"encoding/json"
	"reflect"
	"strings"
	"testing"
)

func TestDimCatalogShape(t *testing.T) {
	axes := DimAxes()
	if !reflect.DeepEqual(axes, []string{"spacing", "layout", "type"}) {
		t.Fatalf("DimAxes() = %v, want [spacing layout type]", axes)
	}
	doc := struct {
		Axes []struct {
			ID     string              `json:"id"`
			Tokens map[string]DimToken `json:"tokens"`
		} `json:"axes"`
	}{}
	if err := json.Unmarshal(dimCatalogJSON, &doc); err != nil {
		t.Fatalf("dim-catalog.json does not parse: %v", err)
	}
	byID := map[string]map[string]DimToken{}
	for _, ax := range doc.Axes {
		if _, dup := byID[ax.ID]; dup {
			t.Fatalf("axis %s listed twice", ax.ID)
		}
		byID[ax.ID] = ax.Tokens
	}
	locked := 0
	var sum float64
	have := map[string]bool{}
	for _, axis := range axes {
		toks := byID[axis]
		if len(toks) == 0 {
			t.Fatalf("axis %s is empty in dim-catalog.json", axis)
		}
		for name, tok := range toks {
			if tok.CSSVar == "" {
				t.Errorf("%s.%s has no cssVar", axis, name)
			}
			if tok.Tier != "validated-range" && tok.Tier != "locked" {
				t.Errorf("%s.%s tier %q is not validated-range or locked", axis, name, tok.Tier)
			}
			switch tok.Unit {
			case "px", "none":
			default:
				t.Errorf("%s.%s unit %q must be px or none", axis, name, tok.Unit)
			}
			if tok.Tier == "locked" {
				locked++
				if name != "docked-min" || axis != "layout" {
					t.Errorf("locked token %s.%s — v1 locks only layout.docked-min", axis, name)
				}
				continue
			}
			v, ok := tok.ParseValue(tok.Default)
			if !ok {
				t.Errorf("%s.%s default %q does not parse", axis, name, tok.Default)
				continue
			}
			if tok.Min != nil && v < *tok.Min {
				t.Errorf("%s.%s default %g is below its own min %g", axis, name, v, *tok.Min)
			}
			if tok.Max != nil && v > *tok.Max {
				t.Errorf("%s.%s default %g is above its own max %g", axis, name, v, *tok.Max)
			}
			switch axis + "." + name {
			case "layout.sidebar", "layout.list-min", "layout.detail-min":
				sum += v
			}
			have[axis+"."+name] = true
		}
	}
	if locked != 1 {
		t.Errorf("locked dimension tokens = %d, want 1 (docked-min)", locked)
	}
	if len(have) != 19 {
		t.Errorf("writable dimension tokens = %d, want 19 (have %v)", len(have), have)
	}
	tok, ok := DimTokenOf("layout", "docked-min")
	if !ok {
		t.Fatal("docked-min missing from catalog")
	}
	v, _ := tok.ParseValue(tok.Default)
	if v != sum {
		t.Errorf("docked-min default %g != sidebar+list-min+detail-min %g — the sum is the contract", v, sum)
	}
}

func TestDimParseLength(t *testing.T) {
	tok := DimToken{Unit: "px"}
	accept := []string{"42px", "44.5px", "1px", " 42px ", "208px", "2200px"}
	for _, s := range accept {
		if v, ok := tok.ParseValue(s); !ok || v <= 0 {
			t.Errorf("ParseValue(%q) = (%g, %v), want ok and positive", s, v, ok)
		}
	}
	reject := []string{"42", "42.25px", "0px", "-42px", "42PX", "42rem", "42 px", "", "4.2e1px", "42em", "calc(42px)", "42pxx"}
	for _, s := range reject {
		if _, ok := tok.ParseValue(s); ok {
			t.Errorf("ParseValue(%q) accepted, want refused", s)
		}
	}
}

func TestDimParseUnitless(t *testing.T) {
	tok := DimToken{Unit: "none"}
	accept := []string{"1.3", "1.15", "1.6", "1.35", "1.4", " 1.22 "}
	for _, s := range accept {
		if _, ok := tok.ParseValue(s); !ok {
			t.Errorf("ParseValue(%q) refused, want accepted", s)
		}
	}
	reject := []string{"1", "1.225", "13", "1.4px", "-1.4", "130%", "1.4.4", ""}
	for _, s := range reject {
		if _, ok := tok.ParseValue(s); ok {
			t.Errorf("ParseValue(%q) accepted, want refused", s)
		}
	}
}

func dimRejects(t *testing.T, axes map[string]map[string]string, wantSub string) {
	t.Helper()
	for _, v := range ValidateDimensions(axes) {
		if v.Severity == SeverityReject {
			if !strings.Contains(v.Message, wantSub) {
				t.Fatalf("reject message %q does not contain %q", v.Message, wantSub)
			}
			return
		}
	}
	t.Fatalf("no reject for %v (want %q)", axes, wantSub)
}

func dimNoReject(t *testing.T, axes map[string]map[string]string) {
	t.Helper()
	for _, v := range ValidateDimensions(axes) {
		if v.Severity == SeverityReject {
			t.Fatalf("unexpected reject: %+v", v)
		}
	}
}

func TestValidateDimensionsAccepts(t *testing.T) {
	dimNoReject(t, map[string]map[string]string{
		"spacing": {"row": "48px", "row-excerpt": "60px", "control-sm": "26px"},
		"layout":  {"sidebar": "300px", "sidebar-narrow": "220px", "detail-max": "800px"},
		"type":    {"body": "14px", "body-line-height": "1.5", "micro": "12px", "title": "16px"},
	})
	dimNoReject(t, map[string]map[string]string{"type": {"heading": "28px"}})
	dimNoReject(t, map[string]map[string]string{"layout": {"shell-max": "2800px"}})
}

func TestValidateDimensionsUnknownCarried(t *testing.T) {
	vs := ValidateDimensions(map[string]map[string]string{
		"radius": {"sm": "4px"},
		"spacing": {
			"row":            "44px",
			"future-renamed": "48px",
		},
	})
	sawUnknownToken, sawUnknownAxis := false, false
	for _, v := range vs {
		if v.Severity == SeverityReject {
			t.Fatalf("unknown names must not refuse: %+v", v)
		}
		if v.Rule == "unknown-token" && v.Token == "future-renamed" {
			sawUnknownToken = true
		}
		if v.Rule == "unknown-axis" && v.Token == "radius" {
			sawUnknownAxis = true
		}
	}
	if !sawUnknownToken {
		t.Errorf("no unknown-token warning: %+v", vs)
	}
	if !sawUnknownAxis {
		t.Errorf("no unknown-axis warning: %+v", vs)
	}
}

func TestValidateDimensionsLocked(t *testing.T) {
	dimRejects(t, map[string]map[string]string{"layout": {"docked-min": "1200px"}}, "locked")
}

func TestValidateDimensionsValues(t *testing.T) {
	dimRejects(t, map[string]map[string]string{"spacing": {"row": "44"}}, "not a px length")
	dimRejects(t, map[string]map[string]string{"spacing": {"row": "60px"}}, "outside")
	dimRejects(t, map[string]map[string]string{"spacing": {"row": "35.9px"}}, "outside")
	dimRejects(t, map[string]map[string]string{"layout": {"shell-max": "1599px"}}, "outside")
	dimRejects(t, map[string]map[string]string{"type": {"body-line-height": "1.7"}}, "outside")
	dimRejects(t, map[string]map[string]string{"type": {"micro": "10.5px"}}, "outside")
}

func TestValidateDimensionsRelations(t *testing.T) {
	// Each relation fires from a one-sided override judged against defaults.
	dimRejects(t, map[string]map[string]string{"spacing": {"control-sm": "34px"}}, "control")
	dimRejects(t, map[string]map[string]string{"spacing": {"row-excerpt": "48px"}}, "row-excerpt")
	dimRejects(t, map[string]map[string]string{"layout": {"detail-max": "430px"}}, "detail-max")
	dimRejects(t, map[string]map[string]string{"layout": {"overlay-max": "2300px"}}, "overlay-max")
	dimRejects(t, map[string]map[string]string{"layout": {"sidebar": "200px"}}, "sidebar")
	// Both sides overridden: the pair is judged as it renders.
	dimRejects(t, map[string]map[string]string{"layout": {"sidebar-narrow": "260px", "sidebar": "280px"}}, "sidebar")
	// Type steps: less than 2px between neighbors reads as noise (census Q6).
	dimRejects(t, map[string]map[string]string{"type": {"title": "14px"}}, "2px")
	dimRejects(t, map[string]map[string]string{"type": {"micro": "13px"}}, "2px")
}

func TestValidateDimensionsBoundaries(t *testing.T) {
	// Inclusive bounds and exact relation edges accept. row at its own max
	// must move row-excerpt with it: the relation judges the effective set,
	// and the default excerpt (59) no longer clears row(56)+8.
	dimNoReject(t, map[string]map[string]string{"spacing": {"row": "36px"}})
	dimNoReject(t, map[string]map[string]string{"spacing": {"row": "56px", "row-excerpt": "72px"}})
	dimNoReject(t, map[string]map[string]string{"spacing": {"control-sm": "32px"}})  // == control default
	dimNoReject(t, map[string]map[string]string{"spacing": {"row-excerpt": "50px"}}) // == row+8
	dimNoReject(t, map[string]map[string]string{"type": {"micro-line-height": "1.15"}})
	dimNoReject(t, map[string]map[string]string{"type": {"heading-line-height": "1.6"}})
}

func TestDimDeterminism(t *testing.T) {
	in := map[string]map[string]string{
		"spacing": {"control": "36px", "control-sm": "28px", "row": "50px"},
		"layout":  {"sidebar": "300px"},
		"type":    {"body": "14px"},
	}
	a, b := ValidateDimensions(in), ValidateDimensions(in)
	if !reflect.DeepEqual(a, b) {
		t.Fatalf("ValidateDimensions not deterministic:\n%+v\n%+v", a, b)
	}
}
