// Package tokencheck validates user color-token overrides (GDK-769 wave,
// GDK-785) with the same color math tools/theme-check.mjs asserts the shipped
// palettes with at build time. User colors arrive at runtime, where the build
// gate cannot see them; this package is the write-time gate and the
// load-time warning source for that surface.
//
// Severity policy (user decision 2026-08-25: "난 대비는 워닝만 떠야지
// 거절은 아니라고 생각해. 대비 뿐 아니라 전반적으로" — judgment warns, only
// machine-checkable conditions refuse): a violation REFUSES when, and only
// when, a machine can see it without taste — a value that cannot parse
// (non-hex color). Everything judgment-shaped — tier, contrast, ΔEok,
// deuteranopia — WARNS and the value is carried: the look is the user's, and
// live filming measured agents burning turns working around refusals. The
// measurements stay in every warning (the diagnostics are unchanged; only
// the verdict moved), and the message teaches the next move instead of
// blocking it.
//
// The two implementations are pinned together by golden vectors:
// tools/theme-check.mjs --emit-vectors writes
// testdata/token-vectors.json from the exact formulas below, and the tests
// consume the full file. A formula that drifts here shows up as a vector
// mismatch, not as a silently different acceptance boundary.
//
// Tier policy (single source: the embedded catalog.json, generated by
// tools/token-catalog.mjs from web/src/app.css — GDK-787):
//
//	locked     10 tokens — grounds (bg-*), text tiers, search-match, shell.
//	           Overrides WARN and save; palette authoring stays
//	           the recommendation (custom-palette scope, GDK-789).
//	validated  12 tokens — accent 4, border 2, status inks 5, focus-ring.
//	           Open for override, judged at write time by the rules below
//	           (warn, not refuse).
//	free       22 tokens — lozenge/avatar/dept chips, scrim, scrollbar-hover.
//	           Any valid hex passes.
//
// Rule derivations — every floor is a current theme-check assertion, carried
// over verbatim (no floor is invented in this package):
//
//	status-pair               pairwise status-ink ΔEok ≥ 0.05
//	                          (theme-check.mjs PAIR_N, checkPairwise)
//	status-pair-deuteranopia  the same pairs after the Machado 2009
//	                          severity-1.0 simulation, ΔEok ≥ 0.04
//	                          (theme-check.mjs PAIR_D, DEUT_M — the matrix
//	                          must not be substituted or transposed)
//	status-role-floor         overridden status ink on each ground:
//	                          ≥ 4.5 on bg-base/panel/elevated (text role),
//	                          ≥ 3 on bg-hover/active (dot role), compared at
//	                          two-decimal rounding like theme-check cr()
//	                          ("status ink floors" + "per-role ink contrast
//	                          floors" sections)
//	accent-text-contrast      accent-text on accent-subtle and on each
//	                          ground ≥ 4.5 — the text-role floor theme-check
//	                          applies to ink-on-ground pairs, applied to the
//	                          surfaces accent-text is actually painted on
//	                          (badges on accent-subtle, keys and links on the
//	                          grounds; measured: every shipped palette clears
//	                          it on all six, minimum 5.27)
//
// Deliberate narrowing (three-part justification, per the GDK-769
// investigation Q2 recommendation adopted 2026-08-24): theme-check also holds
// status-ink loudness RANK invariant across palettes (its "rank" section).
// The runtime does not require rank of an override — rank is taste, not
// legibility; the build assertion stays in force for app.css palettes. Same
// formulas and same thresholds are kept everywhere rank IS legibility.
//
// For accent, accent-hover, accent-subtle, border-subtle, border-strong and
// focus-ring, theme-check carries no named assertion today, so no floor is
// carried for them either — their carried rule is hex validity only, which
// is what their empty extra rule lists in catalog.json record. Adding a real
// floor means theme-check gains the assertion first, then the catalog rules
// lists and this package grow together (GDK-786 hand-off).
//
// Input defense (GDK-769 axis 3): unknown token names are IGNORED with a
// warn-severity violation — a stale schema (a token renamed or removed in a
// newer catalog) must never panic or brick a config write. Malicious or
// corrupt values (huge strings, non-color payloads, truncated hex) are
// rejected as invalid hex; echoed values are truncated so an error message
// cannot be turned into a paste bomb.
package tokencheck

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"maps"
	"math"
	"slices"
	"strconv"
	"strings"
	"sync"
)

// ── color math (mirror of tools/lib/theme-parse.mjs) ──────────────────────

// parseHex mirrors hex2rgb plus the input gate: exactly #rgb or #rrggbb,
// case-insensitive, surrounding whitespace tolerated. The runtime gate is
// intentionally stricter than theme-check hexOf (which tolerates 5–8 digit
// matches as a parser quirk): nothing legitimate produces those shapes, and
// stricter can only refuse, never misread.
func parseHex(s string) ([3]float64, bool) {
	var out [3]float64
	s = strings.ToLower(strings.TrimSpace(s))
	if !strings.HasPrefix(s, "#") {
		return out, false
	}
	h := s[1:]
	if len(h) == 3 {
		h = string([]byte{h[0], h[0], h[1], h[1], h[2], h[2]})
	}
	if len(h) != 6 {
		return out, false
	}
	v, err := strconv.ParseUint(h, 16, 32)
	if err != nil {
		return out, false
	}
	out[0] = float64(v>>16&0xff) / 255
	out[1] = float64(v>>8&0xff) / 255
	out[2] = float64(v&0xff) / 255
	return out, true
}

// ValidHex reports whether s is an acceptable override value.
func ValidHex(s string) bool {
	_, ok := parseHex(s)
	return ok
}

// lin is the sRGB transfer function theme-check uses.
func lin(c float64) float64 {
	if c <= 0.04045 {
		return c / 12.92
	}
	return math.Pow((c+0.055)/1.055, 2.4)
}

func luminance(hex string) float64 {
	r, g, b := parseHex3(hex)
	return 0.2126*lin(r) + 0.7152*lin(g) + 0.0722*lin(b)
}

// Contrast is the WCAG relative-luminance contrast ratio; the lighter side
// is numerator regardless of argument order, as in theme-check.
func Contrast(a, b string) float64 {
	l1, l2 := luminance(a), luminance(b)
	if l1 < l2 {
		l1, l2 = l2, l1
	}
	return (l1 + 0.05) / (l2 + 0.05)
}

// contrastRounded is theme-check cr(): floors are compared at two decimals,
// so the acceptance boundary here is bit-for-bit the same as the gate.
func contrastRounded(a, b string) float64 {
	return math.Round(Contrast(a, b)*100) / 100
}

func parseHex3(hex string) (float64, float64, float64) {
	rgb, _ := parseHex(hex)
	return rgb[0], rgb[1], rgb[2]
}

func hex2oklab(hex string) [3]float64 {
	r, g, b := parseHex3(hex)
	rl := lin(r)
	gl := lin(g)
	bl := lin(b)
	l := math.Cbrt(0.4122214708*rl + 0.5363325363*gl + 0.0514459929*bl)
	m := math.Cbrt(0.2119034982*rl + 0.6806995451*gl + 0.1073969566*bl)
	s := math.Cbrt(0.0883024619*rl + 0.2817188376*gl + 0.6299787005*bl)
	return [3]float64{
		0.2104542553*l + 0.793617785*m - 0.0040720468*s,
		1.9779984951*l - 2.428592205*m + 0.4505937099*s,
		0.0259040371*l + 0.7827717662*m - 0.808675766*s,
	}
}

// DEok is the OKLab Euclidean distance between two hex colors.
func DEok(a, b string) float64 {
	A, B := hex2oklab(a), hex2oklab(b)
	return math.Hypot(A[0]-B[0], math.Hypot(A[1]-B[1], A[2]-B[2]))
}

// Machado 2009 deuteranopia simulation, severity 1.0 — the same matrix
// theme-check pins (do not substitute another; a transposed copy changes
// every non-gray output and the golden deut vectors exist to catch exactly
// that).
var deutM = [3][3]float64{
	{0.367322, 0.860646, -0.227968},
	{0.280085, 0.672501, 0.047413},
	{-0.01182, 0.04294, 0.968881},
}

// Deut maps a hex color through the deuteranopia simulation and returns the
// resulting hex (channels clamped and rounded, like theme-check rgb2hex).
func Deut(hex string) string {
	rgb, _ := parseHex(hex)
	var out [3]float64
	for i, row := range deutM {
		out[i] = row[0]*rgb[0] + row[1]*rgb[1] + row[2]*rgb[2]
	}
	var b strings.Builder
	b.WriteByte('#')
	for _, v := range out {
		if v < 0 {
			v = 0
		}
		if v > 1 {
			v = 1
		}
		fmt.Fprintf(&b, "%02x", int(math.Round(v*255)))
	}
	return b.String()
}

// ── embedded catalog (GDK-787 single source) ──────────────────────────────

//go:embed catalog.json
var catalogJSON []byte

// CatalogToken is one entry of the generated token catalog.
type CatalogToken struct {
	Name        string            `json:"name"`
	CSSVar      string            `json:"cssVar"`
	Tier        string            `json:"tier"`
	Description string            `json:"description"`
	Rules       []string          `json:"rules"`
	Values      map[string]string `json:"values"`
}

type catalogFile struct {
	Source   string         `json:"source"`
	Palettes []string       `json:"palettes"`
	Tokens   []CatalogToken `json:"tokens"`
}

var (
	catalogOnce sync.Once
	catalogVal  catalogFile
	catalogIdx  map[string]CatalogToken
)

func catalog() (catalogFile, map[string]CatalogToken) {
	catalogOnce.Do(func() {
		catalogIdx = make(map[string]CatalogToken)
		if err := json.Unmarshal(catalogJSON, &catalogVal); err != nil {
			// The file is generated and committed; a parse failure is a
			// build defect, not a user-input condition. Leave the zero
			// catalog: every lookup then reports unknown, which refuses
			// writes loudly instead of panicking.
			return
		}
		for _, t := range catalogVal.Tokens {
			catalogIdx[t.Name] = t
		}
	})
	return catalogVal, catalogIdx
}

// CatalogTokens returns the embedded catalog in file (app.css) order.
func CatalogTokens() []CatalogToken {
	c, _ := catalog()
	return c.Tokens
}

// CatalogPalettes returns the palette axis (light first, then data-theme
// blocks in sorted order).
func CatalogPalettes() []string {
	c, _ := catalog()
	return c.Palettes
}

// TierOf reports the tier of a token, by bare name ("accent") or CSS
// variable name ("--color-accent"). ok is false for names the catalog does
// not carry.
func TierOf(name string) (tier string, ok bool) {
	_, idx := catalog()
	t, ok := idx[normalizeTokenName(name)]
	return t.Tier, ok
}

// CatalogValue returns the catalog value of a token in one palette.
func CatalogValue(name, palette string) (string, bool) {
	_, idx := catalog()
	t, ok := idx[name]
	if !ok {
		return "", false
	}
	v, ok := t.Values[palette]
	return v, ok
}

// ── validation ────────────────────────────────────────────────────────────

// Severity of a violation. Reject means the write must be refused; warn
// means the input is carried but the user must be told.
type Severity string

const (
	SeverityReject Severity = "reject"
	SeverityWarn   Severity = "warn"
)

// Violation is one rule outcome. Measured and Floor carry the real numbers
// so an agent can fix its own color without a round trip.
type Violation struct {
	Token    string   `json:"token"`
	Rule     string   `json:"rule"`
	Severity Severity `json:"severity"`
	Measured string   `json:"measured,omitempty"`
	Floor    string   `json:"floor,omitempty"`
	Message  string   `json:"message"`
}

// Floors and axes, all derived from theme-check (see package comment).
const (
	pairNormal      = 0.05
	pairDeut        = 0.04
	floorText       = 4.5
	floorDot        = 3.0
	accentTextFloor = 4.5
)

// STATS and GROUNDS in theme-check order, so violation order is stable.
var (
	statusTokens = []string{"status-new", "status-inprogress", "status-done", "status-reopen", "status-stale"}
	groundTokens = []string{"bg-base", "bg-panel", "bg-elevated", "bg-hover", "bg-active"}
)

// implementedRules is the set of rule ids this package can enforce; the test
// asserts the catalog never references one outside it (catalog drift check,
// Go side — token-catalog.mjs --check covers the app.css side).
var implementedRules = map[string]bool{
	"hex":                      true,
	"status-pair":              true,
	"status-pair-deuteranopia": true,
	"status-role-floor":        true,
	"accent-text-contrast":     true,
}

const tokenPrefix = "--color-"

// normalizeTokenName accepts the bare catalog name or its CSS variable form.
func normalizeTokenName(k string) string {
	k = strings.TrimSpace(k)
	return strings.TrimPrefix(k, tokenPrefix)
}

// quote echoes a user-supplied value in a message, truncated so a hostile
// value cannot flood the error output.
func quote(v string) string {
	const max = 40
	if len(v) > max {
		v = v[:max] + "…"
	}
	return `"` + v + `"`
}

// ValidateTokens checks a partial set of color-token overrides against the
// tier policy. Keys are bare token names ("accent") or CSS variable names
// ("--color-accent"); values are hex colors. base is the palette the
// overrides will be applied to (name → raw value, hex for everything the
// rules read); tokens the caller did not override are filled from it, so a
// one-token override is checked in the context it will actually render in.
//
// The result is deterministic for identical inputs: per-token checks run in
// sorted name order, group rules in STATS/GROUNDS order. Duplicate keys that
// normalize to the same name (both "--color-x" and "x") resolve last-wins in
// sorted key order, like CSS. Unknown names never panic: they produce a
// warn violation and are ignored.
func ValidateTokens(overrides, base map[string]string) []Violation {
	if len(overrides) == 0 {
		return nil
	}
	_, idx := catalog()

	// Resolve keys in sorted order so "--color-x" and "x" colliding is
	// deterministic (last wins, like CSS) and per-token output is sorted.
	keys := slices.Sorted(maps.Keys(overrides))
	resolved := make(map[string]string, len(overrides))
	for _, k := range keys {
		resolved[normalizeTokenName(k)] = overrides[k]
	}
	names := slices.Sorted(maps.Keys(resolved))

	var vs []Violation
	// eff is the effective palette: base with valid overrides applied. Group
	// rules judge what renders, not what was typed.
	eff := make(map[string]string, len(base)+len(resolved))
	for k, v := range base {
		eff[k] = v
	}
	overridden := map[string]bool{} // valid overrides (rule participants)

	for _, name := range names {
		value := resolved[name]
		tok, known := idx[name]
		if !known {
			vs = append(vs, Violation{
				Token:    name,
				Rule:     "unknown-token",
				Severity: SeverityWarn,
				Measured: quote(value),
				Message:  fmt.Sprintf("--color-%s is not in the color catalog; ignored (a newer catalog may have renamed it)", name),
			})
			continue
		}
		if tok.Tier == "locked" {
			// The tier is a judgment, not a machine check — warn, save,
			// and keep the palette-authoring recommendation in the message.
			vs = append(vs, Violation{
				Token:    name,
				Rule:     "locked",
				Severity: SeverityWarn,
				Measured: quote(value),
				Message:  fmt.Sprintf("--color-%s is locked (%s) — applied, but locked tokens are palette authoring: the build may re-derive them in an upgrade; per-palette opening is the custom-palette scope (GDK-789)", name, tok.Description),
			})
			continue
		}
		if !ValidHex(value) {
			vs = append(vs, Violation{
				Token:    name,
				Rule:     "hex",
				Severity: SeverityReject,
				Measured: quote(value),
				Floor:    "#rgb or #rrggbb",
				Message:  fmt.Sprintf("--color-%s: %s is not a #rgb or #rrggbb hex color", name, quote(value)),
			})
			continue
		}
		eff[name] = value
		overridden[name] = true
	}

	// Group rules: only run for families that were actually overridden, and
	// only when the effective palette has every color the rule reads.
	hexOK := func(names ...string) ([]string, bool) {
		var missing []string
		for _, n := range names {
			if !ValidHex(eff[n]) {
				missing = append(missing, n)
			}
		}
		return missing, len(missing) == 0
	}

	statusTouched := false
	for _, s := range statusTokens {
		if overridden[s] {
			statusTouched = true
		}
	}
	if statusTouched {
		need := append(append([]string{}, statusTokens...), groundTokens...)
		if missing, ok := hexOK(need...); !ok {
			vs = append(vs, Violation{
				Token:    "palette",
				Rule:     "base-incomplete",
				Severity: SeverityWarn,
				Measured: strings.Join(missing, ", "),
				Message:  "status rules skipped: base palette is missing or non-hex for " + strings.Join(missing, ", "),
			})
		} else {
			vs = append(vs, checkStatusPairs(eff, overridden)...)
			vs = append(vs, checkStatusRoleFloors(eff, overridden)...)
		}
	}

	if overridden["accent-text"] || overridden["accent-subtle"] {
		need := append([]string{"accent-text", "accent-subtle"}, groundTokens...)
		if missing, ok := hexOK(need...); !ok {
			vs = append(vs, Violation{
				Token:    "palette",
				Rule:     "base-incomplete",
				Severity: SeverityWarn,
				Measured: strings.Join(missing, ", "),
				Message:  "accent-text rule skipped: base palette is missing or non-hex for " + strings.Join(missing, ", "),
			})
		} else {
			vs = append(vs, checkAccentText(eff)...)
		}
	}

	return vs
}

// blame names the token a pair violation belongs to: the overridden half of
// the pair when exactly one was overridden, both names otherwise.
func blame(overridden map[string]bool, a, b string) string {
	oa, ob := overridden[a], overridden[b]
	switch {
	case oa && !ob:
		return a
	case ob && !oa:
		return b
	default:
		return a + "/" + b
	}
}

// checkStatusPairs runs the pairwise separation rules over the effective
// palette: ΔEok ≥ 0.05 as-is and ≥ 0.04 under the deuteranopia simulation
// (theme-check PAIR_N / PAIR_D).
func checkStatusPairs(eff map[string]string, overridden map[string]bool) []Violation {
	var vs []Violation
	for i := 0; i < len(statusTokens); i++ {
		for j := i + 1; j < len(statusTokens); j++ {
			a, b := statusTokens[i], statusTokens[j]
			ah, bh := eff[a], eff[b]
			if n := DEok(ah, bh); n < pairNormal {
				vs = append(vs, Violation{
					Token:    blame(overridden, a, b),
					Rule:     "status-pair",
					Severity: SeverityWarn,
					Measured: fmt.Sprintf("%.4f", n),
					Floor:    "0.05",
					Message: fmt.Sprintf("status inks %s/%s (%s/%s) ΔEok %.4f < 0.05 — applied, but the two states will read as one",
						trimStatus(a), trimStatus(b), ah, bh, n),
				})
			}
			d := DEok(Deut(ah), Deut(bh))
			if d < pairDeut {
				vs = append(vs, Violation{
					Token:    blame(overridden, a, b),
					Rule:     "status-pair-deuteranopia",
					Severity: SeverityWarn,
					Measured: fmt.Sprintf("%.4f", d),
					Floor:    "0.04",
					Message: fmt.Sprintf("status inks %s/%s (%s/%s) ΔEok %.4f < 0.04 under deuteranopia (%s/%s simulated) — applied, but deutan readers lose the pair",
						trimStatus(a), trimStatus(b), ah, bh, d, Deut(ah), Deut(bh)),
				})
			}
		}
	}
	return vs
}

func trimStatus(name string) string {
	return strings.TrimPrefix(name, "status-")
}

// checkStatusRoleFloors: each overridden status ink on each ground, ≥4.5 in
// text role (base/panel/elevated), ≥3 in dot role (hover/active), compared
// at two decimals like theme-check cr().
func checkStatusRoleFloors(eff map[string]string, overridden map[string]bool) []Violation {
	var vs []Violation
	for _, s := range statusTokens {
		if !overridden[s] {
			continue
		}
		for _, g := range groundTokens {
			floor := floorText
			role := "text"
			if g == "bg-hover" || g == "bg-active" {
				floor = floorDot
				role = "dot"
			}
			v := contrastRounded(eff[s], eff[g])
			if v < floor {
				vs = append(vs, Violation{
					Token:    s,
					Rule:     "status-role-floor",
					Severity: SeverityWarn,
					Measured: fmt.Sprintf("%.2f", v),
					Floor:    fmt.Sprintf("%.1f", floor),
					Message: fmt.Sprintf("%s %s as %s on %s %s: contrast %.2f < %.1f — applied, but it will read thin; pick a darker (text) or higher-chroma ink",
						s, eff[s], role, g, eff[g], v, floor),
				})
			}
		}
	}
	return vs
}

// checkAccentText: accent-text on accent-subtle and on each ground ≥ 4.5.
func checkAccentText(eff map[string]string) []Violation {
	var vs []Violation
	surfaces := append([]string{"accent-subtle"}, groundTokens...)
	for _, g := range surfaces {
		v := contrastRounded(eff["accent-text"], eff[g])
		if v < accentTextFloor {
			vs = append(vs, Violation{
				Token:    "accent-text",
				Rule:     "accent-text-contrast",
				Severity: SeverityWarn,
				Measured: fmt.Sprintf("%.2f", v),
				Floor:    "4.5",
				Message: fmt.Sprintf("accent-text %s on %s %s: contrast %.2f < 4.5 — applied, but badge/link text will be hard to read",
					eff["accent-text"], g, eff[g], v),
			})
		}
	}
	return vs
}
