import type { APIRoute } from 'astro'

/**
 * The sitemap, written out rather than generated by an integration.
 *
 * This site owns six pages. An explicit list is shorter than the dependency
 * that would discover them, and it fails loudly — a new page missing here is
 * a line someone forgot, not a silent crawl gap in a plugin's glob. The demo
 * and backlog apps are deliberately absent: they belong to the hosted-demo
 * build (tools/hosted-demo/build.mjs), and a hash-routed app has exactly one
 * URL to offer anyway.
 *
 * Each entry carries both languages as alternates, which is what stops the
 * en and ko pages from competing with each other for the same query.
 */
const SITE = 'https://gadak.dev'

/** en path → the same page in ko. */
const PAGES: Array<{ en: string; ko: string; priority: string }> = [
  { en: '/', ko: '/ko/', priority: '1.0' },
  { en: '/install/', ko: '/ko/install/', priority: '0.8' },
  { en: '/changelog/', ko: '/ko/changelog/', priority: '0.7' },
]

function urlEntry(loc: string, alternates: Array<{ lang: string; href: string }>, priority: string) {
  const links = alternates
    .map((a) => `    <xhtml:link rel="alternate" hreflang="${a.lang}" href="${SITE}${a.href}"/>`)
    .join('\n')
  return `  <url>
    <loc>${SITE}${loc}</loc>
${links}
    <priority>${priority}</priority>
  </url>`
}

export const GET: APIRoute = () => {
  const body = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
${PAGES.flatMap((p) => {
  const alternates = [
    { lang: 'en', href: p.en },
    { lang: 'ko', href: p.ko },
    { lang: 'x-default', href: p.en },
  ]
  return [urlEntry(p.en, alternates, p.priority), urlEntry(p.ko, alternates, p.priority)]
}).join('\n')}
</urlset>
`
  return new Response(body, { headers: { 'Content-Type': 'application/xml; charset=utf-8' } })
}
