import type { APIRoute } from 'astro'

import { listEssays } from '../lib/essays'
import { LOCALES, pathFor } from '../i18n'

/**
 * The sitemap, written out rather than generated by an integration.
 *
 * The locale pages are an explicit list. It is shorter than the dependency
 * that would discover them, and it fails loudly — a new page missing here is
 * a line someone forgot, not a silent crawl gap in a plugin's glob. The demo
 * and backlog apps are deliberately absent: they belong to the hosted-demo
 * build (tools/hosted-demo/build.mjs), and a hash-routed app has exactly one
 * URL to offer anyway.
 *
 * The essays are the one exception, enumerated from their source directory
 * (src/lib/essays.ts): the .md file is itself the registration, so a
 * discovery pass here would be a second copy of the same list.
 *
 * Each locale entry carries every locale as alternates, which is what
 * stops the mirrored pages from competing with each other for the same
 * query. Essays are en-only canonical and claim no alternates — an
 * hreflang that 404s would be worse than none.
 */
const SITE = 'https://gadak.dev'

/**
 * en path → one row per locale (pathFor derives each locale's URL).
 *
 * /privacy/ is absent on purpose: it is the orphan page app-store listings
 * point at (GDK-1380), not something a crawler should rank — no nav link, no
 * sitemap line, no mirrors.
 */
const PAGES: Array<{ en: string; priority: string }> = [
  { en: '/', priority: '1.0' },
  { en: '/install/', priority: '0.8' },
  { en: '/changelog/', priority: '0.7' },
]

function urlEntry(loc: string, alternates: Array<{ lang: string; href: string }>, priority: string) {
  const links = alternates
    .map((a) => `    <xhtml:link rel="alternate" hreflang="${a.lang}" href="${SITE}${a.href}"/>`)
    .join('\n')
  // Line list rather than a template literal so an entry with no alternates
  // (the essays) drops the links line instead of leaving a blank one.
  return [
    '  <url>',
    `    <loc>${SITE}${loc}</loc>`,
    links,
    `    <priority>${priority}</priority>`,
    '  </url>',
  ]
    .filter((line) => line !== '')
    .join('\n')
}

export const GET: APIRoute = async () => {
  const essays = await listEssays()
  const body = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
${[
  ...PAGES.flatMap((p) => {
    const alternates = [
      ...LOCALES.map((l) => ({ lang: l, href: pathFor(l, p.en) })),
      { lang: 'x-default', href: p.en },
    ]
    return LOCALES.map((l) => urlEntry(pathFor(l, p.en), alternates, p.priority))
  }),
  urlEntry('/essays/', [], '0.6'),
  ...essays.map((e) => urlEntry(`/essays/${e.slug}/`, [], '0.5')),
].join('\n')}
</urlset>
`
  return new Response(body, { headers: { 'Content-Type': 'application/xml; charset=utf-8' } })
}
