// The bundled demo workspace (GDK-1051): a read-only sample mirror frozen
// under /demo/ (mobile/public/demo, regenerated by
// mobile/scripts/demo-snapshot.sh) and served by the app's own origin —
// Vite's publicDir in dev, the packaged webview's asset origin in a build.
// window.fetch is the only transport here: plugin-http speaks http(s), not
// the asset protocol, and the demo never leaves the origin anyway.
//
// Ownership: request() in api.ts delegates every call here while a demo
// session is active (one line there; this module is the whole branch). The
// store's enterDemo()/exitDemo() flip the session flag and own the
// no-persistence contract — nothing in this module reads or writes
// localStorage or the Keychain.

import { ApiError, type Envelope, type FetchLike } from './api'

let demoSession = false

/** True while the bundled demo workspace is the active session. */
export function isDemoSession(): boolean {
  return demoSession
}

/** Flipped only by the store's enterDemo()/exitDemo(), never by a screen. */
export function setDemoSession(on: boolean): void {
  demoSession = on
}

function jsonResponse(doc: unknown, status = 200): Response {
  return new Response(JSON.stringify(doc), {
    status,
    headers: { 'Content-Type': 'application/json' },
  })
}

function errorResponse(code: string, status: number): Response {
  return jsonResponse({ error: code }, status)
}

/** `issues/<KEY>/detail/` — a Jira-shaped key, so the URL cannot wander. */
const DETAIL_PATH = /^issues\/([A-Za-z][A-Za-z0-9]*-[0-9]+)\/detail\/$/
const TRANSITIONS_PATH = /^issues\/[A-Za-z][A-Za-z0-9]*-[0-9]+\/transitions\/$/

/** Bundled-file URLs; null means the path gets a synthesized response. */
function demoAssetUrl(path: string): string | null {
  if (path === 'issues/bootstrap/') return '/demo/bootstrap.json'
  const detail = DETAIL_PATH.exec(path)
  if (detail) return `/demo/detail/${detail[1]}.json`
  return null
}

/**
 * Synthesized GET responses, shaped exactly as the phone parses them
 * (types.ts / domain.ts) — the same rows the web hosted demo synthesizes
 * (web/src/lib/hosted-fetch.ts), adapted to the phone's wire types.
 */
function demoSynthetic(path: string): Response {
  if (path === 'auth/me/') {
    // Standalone-shape identity: no email, no account — the PairingTab's
    // "no identity" copy and the Mine scope degrade exactly as they do
    // against a credential-less serve.
    return jsonResponse({ email: null, account_id: null, name: null })
  }
  if (path === 'issues/views/') {
    // ViewsResponse (types.ts): the scope picker falls back to its two
    // hardcoded scopes, same as a serve that refuses the view list.
    return jsonResponse({ views: [], source: [] })
  }
  if (path.startsWith('issues/feed')) {
    // FeedResponse (domain.ts) with zero unread: the glance strip is absent,
    // not an error box — matching the empty-feed degradation.
    return jsonResponse({
      items: [],
      unread_counts: { all: 0, assignee: 0, reporter: 0, mention: 0 },
    })
  }
  if (TRANSITIONS_PATH.test(path)) {
    // The transitions sheet exists only to fire a write. Answering it with
    // the serve's own write refusal rides Detail's existing writes-off
    // degradation (409 credential_required) instead of inventing a code.
    return errorResponse('credential_required', 409)
  }
  // v1 demo has no wiki pages, and search is local-first over the snapshot:
  // the web hosted demo answers both of these 404 as well.
  return errorResponse('not_found', 404)
}

/**
 * The demo branch of request(): same envelope and error contract, sourced
 * from the bundle. Writes never fetch — they get the serve's refusal so the
 * write controls degrade instead of pretending to succeed.
 */
export async function demoRequest<T>(
  path: string,
  opts: { method?: string; fetchFn?: FetchLike } = {},
): Promise<Envelope<T>> {
  const method = (opts.method ?? 'GET').toUpperCase()
  if (method !== 'GET' && method !== 'HEAD') {
    throw new ApiError('credential_required', 409)
  }
  const url = demoAssetUrl(path)
  const doFetch = opts.fetchFn ?? ((u: string, init: RequestInit) => window.fetch(u, init))
  let res: Response
  try {
    res = url !== null ? await doFetch(url, { method: 'GET' }) : demoSynthetic(path)
  } catch {
    throw new ApiError('network', 0)
  }
  if (!res.ok) {
    let code = 'internal_error'
    try {
      const doc = (await res.json()) as { error?: unknown }
      if (typeof doc.error === 'string' && doc.error !== '') code = doc.error
    } catch {
      // Non-JSON error body (the asset origin's own 404 page): generic code.
    }
    throw new ApiError(code, res.status)
  }
  let body: T
  try {
    body = (await res.json()) as T
  } catch {
    throw new ApiError('bad_response', res.status)
  }
  return { status: res.status, etag: res.headers.get('ETag'), body }
}
